services:
  pytorch:
    container_name: l4t-pytorch
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /home/xavier/:/workspace
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/ttyUSB0
    network_mode: host
    user: 1000:1000
    privileged: true
    runtime: nvidia
    group_add: 
      - video
      - dialout
    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
      QT_X11_NO_MITSHM: 1
      QT_DEBUG_PLUGINS: 1 
      ROS_LOCALHOST_ONLY: 1
    
    tty: true
    stdin_open: true    
    working_dir: /workspace
